
service: sls-unit-test

frameworkVersion: '2'

custom:
  GREETER_DYNAMODB_TABLE: sls-unit-test-names-table
 
provider:
  name: aws 
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment: ${self:custom}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
      Resource:
        Fn::GetAtt:
          - GreeterTable
          - Arn

functions:
  hello:
    handler: handler.hello
    description: "just simple hello world"
    events:
      - http:
          method: get
          path: hello
  moi:
    handler: handler.moi
    description: "Saves the name to a database and says hi"
    events: 
      - http:
          method: get
          path: moi
  wasGreeted:
    handler: handler.wasGreeted
    description: "Returns 200 if the name was greeted already - 404 if not"
    events:
      - http:
          method: get
          path: greet

resources:
  Resources:
    GreeterTables:
      Type: "AWS::DynamoTableDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.GREETER_DYNAMODB_TABLE}
